### PR TITLE
Clean up of the Readme

### PR DESCRIPTION
**Pull request by blink1073**
Hi @yxdragon, as promised, here are some clean ups.

### CODE REVIEW

**Comment by yxdragon** [comment]
@blink1073 
Thanks very much. and forgave my bad English.
I am doing some work to improve ImagePy, such as multi-thread support when running a plugin.
I will use the wxphonix in this project, but I have heard some voice that QT is better.
need I support both(it 's not difficult)?

What to do next:
1.rewrite the home page into English.
2.thouthands of authers contribute ImageJ plugins, I will write a scripts to got the list and mail to them.
3.perhaps, wrap scikit-image completely with some sample pictures and documents, That will be a good interactive tutorial!

Do you have some advice?

**Comment by blink1073** [comment]
Hi @yxdragon, my pleasure.  I'd say concentrate on wx for now, supporting both is not much fun.  I would avoid sending a individual emails, a post on the ImageJ mailing list seems more appropriate.  As for scikit-image, I'd recommend starting with one small part, and opening an issue asking for help with the rest.

**Comment by yxdragon** [comment]
@blink1073 I had support the wx-phoenix, and I have some other question.
How to show a numpy array in a wxpanel?
now my step is:
1.wx.Image.setdata(numpy.getbuffer)
2.scale the image
3.translate image to bitmap
4.draw the bitmap
but it cost all cpu when the image is (2048*2048), but imagej can show the same image well.
and I saw the imagej's sorcecode, just graphic.draw. do you know how to draw numpy  efficiently in wx?

another one:
need I to write another branch to support the python3.x? or there is some tools to convert code auto? or I write some 'if ... else ...' in the code to adapte the version?

**Comment by blink1073** [comment]
Hi @yxdragon, it has been years since I last used `wx`, I'm afraid I do not know much about the optimization aspect.  Typically projects add a utility file that smooths out the differences between python versions, for example: https://github.com/blink1073/oct2py/blob/master/oct2py/compat.py.  Using `from __future__ import division, print_function, absolute_import` at the top of all files helps as well.  Also, you can use the [six](https://github.com/benjaminp/six) package if needed.

**Pull request merged**
